const fs = require('fs-extra');
const path = require('path');
const axios = require('axios');
const gis = require('g-i-s');

// --- CONFIGURAÇÕES ---
const DELAY_ENTRE_BUSCAS = 2000; // 2 segundos (Google bloqueia se for muito rápido)
const ARQUIVO_ADULTO_PADRAO = 'padrao_adulto.jpg'; // O arquivo que você salvou na raiz

// Pastas de destino
const DIR_FILMES = path.join(__dirname, 'public', 'covers', 'movies');
const DIR_SERIES = path.join(__dirname, 'public', 'covers', 'series');

// SUA LISTA DE ERROS (Colei o JSON que você mandou)
const ITENS_PARA_CORRIGIR = [
    { "id": 8206, "nome": "Taxitramas", "tipo": "series" },
    { "id": 8179, "nome": "Brasil 2050", "tipo": "series" },
    { "id": 8018, "nome": "Krypto Salva o Dia", "tipo": "series" },
    { "id": 7313, "nome": "The Adventures of a Demon Kings Daughter [L]", "tipo": "series" },
    { "id": 6160, "nome": "Tributo", "tipo": "series" },
    { "id": 6176, "nome": "Maniaco do Parque A Historia Nao Contada", "tipo": "series" },
    { "id": 4191, "nome": "Leandro e Leonardo", "tipo": "series" },
    { "id": 4285, "nome": "Valley of Flood and Fire", "tipo": "series" },
    { "id": 4096, "nome": "Global Citizen Festival", "tipo": "series" },
    { "id": 3752, "nome": "KAMEN RIDER GEATS [L]", "tipo": "series" },
    { "id": 3588, "nome": "Love Touch", "tipo": "series" },
    { "id": 3570, "nome": "Expedicao Cicloturismo A Vida em Movimento", "tipo": "series" },
    { "id": 3362, "nome": "A Vida Interior Com o Padre Paulo Ricardo", "tipo": "series" },
    { "id": 3289, "nome": "Carnaval RJ (2023)", "tipo": "series" },
    { "id": 3093, "nome": "Love Never Lies: Destination Sardinia", "tipo": "series" },
    { "id": 2862, "nome": "Dr. Delirium e os Experimentos em Edgewood", "tipo": "series" },
    { "id": 1337, "nome": "Guga Guns", "tipo": "series" },
    { "id": 639, "nome": "Vampiros da Mata da Serreta", "tipo": "series" },
    { "id": 314641, "nome": "[XXX] Crazycollegegfs 2024 04 27 Addis Fouché Ameena Green Gizelle Blanco Alex Jones College Vacation Part 2 [Adulto]", "tipo": "movies" },
    { "id": 314640, "nome": "[XXX] Crazycollegegfs 2024 04 22 Addis Fouché Ameena Green Gizelle Blanco Scott Nails College Vacation Part [Adulto]", "tipo": "movies" },
    { "id": 311364, "nome": "Casada Trouxe Negão Para Foder Ela Na Frente Do Marido Corno", "tipo": "movies" },
    { "id": 311362, "nome": "A Princesinha Da Minha Irmã", "tipo": "movies" },
    { "id": 311361, "nome": "Colocou A Calcinha No Meio Das Roupas Do Irmão Com Segundas Intenções", "tipo": "movies" },
    { "id": 311357, "nome": "Irmãos Ficaram De Castigo No Mesmo Quarto", "tipo": "movies" },
    { "id": 311354, "nome": "Acordando O Meio-irmão Com Uma Punheta", "tipo": "movies" },
    { "id": 311355, "nome": "Garota Foi Pega Usando Cartões Clonados", "tipo": "movies" },
    { "id": 311352, "nome": "Anal Surpresa Na Madrasta Puta – Pervmom", "tipo": "movies" },
    { "id": 311349, "nome": "Cookies para o Papai Noel – MomsTeachSex", "tipo": "movies" },
    { "id": 311348, "nome": "comeu e gozou dentro da irmã, enquanto ela falava ao telefone com o namorado", "tipo": "movies" },
    { "id": 311345, "nome": "Irmã E Amiga Fazendo Irmão Gozar", "tipo": "movies" },
    { "id": 311341, "nome": "Minha Irmã Não Usa Roupa Dentro De Casa – Primalfetish", "tipo": "movies" },
    { "id": 311342, "nome": "Loira Bunduda Transa Com Médico Após Tomar O Viagra Feminino E Ficar Com O Maior Tesão", "tipo": "movies" },
    { "id": 311334, "nome": "Enviando Um Video Especial Para O Filho Que Está Viajando – Xevbellringer", "tipo": "movies" },
    { "id": 311337, "nome": "Duas Mãe São Melhores Que Uma – Youngermommy", "tipo": "movies" },
    { "id": 311329, "nome": "Garota Se Vingou Da Traição Do Namorado, Fodendo Com Seu Irmão", "tipo": "movies" },
    { "id": 311333, "nome": "A Madrasta Gostosa Prometeu Um Boquete Para Seu Enteado, Caso Ele Tire Boas Notas No Próximo Semestr", "tipo": "movies" },
    { "id": 311332, "nome": "Irmãs Sentando A Boceta No Irmão", "tipo": "movies" },
    { "id": 311330, "nome": "Ajudando A Irmã Com Seu Dever De Casa", "tipo": "movies" },
    { "id": 311324, "nome": "Fodendo A Irmã Salva Vidas", "tipo": "movies" },
    { "id": 311328, "nome": "Negão Comendo A Vizinha Gostosa", "tipo": "movies" },
    { "id": 311327, "nome": "Mamãe Está Com Ciúmes Da Minha Namorada – Xevbellringer", "tipo": "movies" },
    { "id": 311326, "nome": "Foda Quente Entre Irmão E Irmã", "tipo": "movies" },
    { "id": 311320, "nome": "Garotas Do Antifa Roubaram Loja, E Tiveram Que Transar Com O Guarda Da Loja Senão Seriam Denunciadas", "tipo": "movies" },
    { "id": 311319, "nome": "A Irmã Gostosa Precisava Treinar Corte De Cabelo", "tipo": "movies" },
    { "id": 311314, "nome": "Comendo A Bucetinha Quente Da Irmã", "tipo": "movies" },
    { "id": 311310, "nome": "Irmã Gamer Futucando O Bucetão", "tipo": "movies" },
    { "id": 311312, "nome": "Casada Fez Teste Para Ser A Professora De Educação Sexual", "tipo": "movies" },
    { "id": 311311, "nome": "Alguns Dólares Para Minha Enteada", "tipo": "movies" },
    { "id": 311308, "nome": "Ménage Entre Irmãos", "tipo": "movies" },
    { "id": 311307, "nome": "Grávida Casada Fodeu Com Desconhecido Para Quitar A Dívida Da Loja", "tipo": "movies" },
    { "id": 311304, "nome": "O Cara Armou Para Seu Amigo Negro Comer A Sua Irmã", "tipo": "movies" },
    { "id": 311305, "nome": "Garçonete Com Peitos Deliciosos Não Resistiu Ao Dinheiro E Transou Com Cliente", "tipo": "movies" },
    { "id": 311302, "nome": "Gozando Nos Peitos Da Mamãe", "tipo": "movies" },
    { "id": 311301, "nome": "Sogra Viúva Carente De Sexo", "tipo": "movies" },
    { "id": 311299, "nome": "Cheirando As Calcinhas Da Irmã", "tipo": "movies" },
    { "id": 311300, "nome": "Mãe Implorando Por Gozada Na Buceta", "tipo": "movies" },
    { "id": 311298, "nome": "Esposa Asiática Realizando A Fantasia Do Marido De Ser Corno", "tipo": "movies" },
    { "id": 311297, "nome": "dormindo com o enteado antes da competição de xadrez", "tipo": "movies" },
    { "id": 311294, "nome": "Dando A Boceta Pro Irmão Como Presente De Aniversário", "tipo": "movies" },
    { "id": 311289, "nome": "Fodendo Com O Diretor Da Escola Para O Filho Não Ser Expuldo", "tipo": "movies" },
    { "id": 311290, "nome": "Mulher Deu Pra 2 Em Troca De Participação Em Um Reality Show", "tipo": "movies" },
    { "id": 311291, "nome": "Mãe Porno Sentando A Buceta No Filho", "tipo": "movies" },
    { "id": 311284, "nome": "Francesa Em Apuros Deu A Boceta Para Conseguir Voltar Pro Seu País", "tipo": "movies" },
    { "id": 311287, "nome": "Magrinha Aceita A Massagem Grátis E Trai Seu Marido Com O Massagista", "tipo": "movies" },
    { "id": 311286, "nome": "Loira Foi Tomar O Viagra Feminino Para Resolver Seu Problema E Acabou Fodendo Com O Médico", "tipo": "movies" },
    { "id": 311280, "nome": "Enteada Pega Com Tesão", "tipo": "movies" },
    { "id": 311282, "nome": "Milf Gostosa Fodeu Com Cara, Para Que Seu Filho Não Seja Expulso Da Escola", "tipo": "movies" },
    { "id": 311281, "nome": "Novinha Deu Pro Médico Para Poder Jogar O Campeonato De Vôlei", "tipo": "movies" },
    { "id": 311275, "nome": "Mostrando Aos Enteados Como Tratar Uma Garota – Momswap", "tipo": "movies" },
    { "id": 311276, "nome": "costureira gostosa não resistiu ao pauzão do negão e fodeu com ele", "tipo": "movies" },
    { "id": 311277, "nome": "Enteada Com Fetiche Em Ser Observada Pelo Pai – Meanawolf", "tipo": "movies" },
    { "id": 311278, "nome": "Comendo A Irmã Loira Ladra De Camisinhas", "tipo": "movies" },
    { "id": 311274, "nome": "Homem Comeu A Ruivinha Após Fazer Algumas Perguntas", "tipo": "movies" },
    { "id": 311270, "nome": "Acabou de terminar o namoro e pediu pau pro irmão – XevBellringer", "tipo": "movies" },
    { "id": 311266, "nome": "Lana A Irmã Gostosa", "tipo": "movies" },
    { "id": 311265, "nome": "Estudar Ou Chupar – Dadcrush", "tipo": "movies" },
    { "id": 311264, "nome": "Garota Safada Provocou Seu Irmão Até Ser Fodida", "tipo": "movies" },
    { "id": 311268, "nome": "Mãe Sentando No Pau Do Enteado", "tipo": "movies" },
    { "id": 311261, "nome": "Namorado Afro Metendo Na Mãe E Na Filha", "tipo": "movies" },
    { "id": 311259, "nome": "Não Goze Na Mamãe", "tipo": "movies" },
    { "id": 311262, "nome": "Comendo A Irmã E Sua Amiga Novinha", "tipo": "movies" },
    { "id": 311260, "nome": "Não Conte Ao Papai", "tipo": "movies" },
    { "id": 311257, "nome": "Chantageou A Irmã Que Tava Dando Pro Ursinho De Pelucia", "tipo": "movies" },
    { "id": 311254, "nome": "Ensinando Lições Ao Filho", "tipo": "movies" },
    { "id": 311255, "nome": "Mãe Flagrou A Filha Transando – Parte 2", "tipo": "movies" },
    { "id": 311258, "nome": "comi minha irmã gostosa na cama dela", "tipo": "movies" },
    { "id": 311251, "nome": "Meio-irmão Fez Um Joguinho Para Foder A Irmã", "tipo": "movies" },
    { "id": 311250, "nome": "Massagista Ofereceu Massagem Grátis Para Comer A Novinha", "tipo": "movies" },
    { "id": 311253, "nome": "Fazendo A Irmã Transar Com Seu Namorado", "tipo": "movies" },
    { "id": 311248, "nome": "Madrasta Pegou No Flagra Os Irmãos Transando", "tipo": "movies" },
    { "id": 311245, "nome": "Garotas Fazendo De Tudo Para Conseguir Permissão Para Ir Na Viagem Da Escola", "tipo": "movies" },
    { "id": 311246, "nome": "Irmã Fazendo Exercícios Para Deixar O Irmão Com Tesão E Comer Ela", "tipo": "movies" },
    { "id": 311243, "nome": "Ajudando O Papai A Gozar – Familytherapy", "tipo": "movies" },
    { "id": 311241, "nome": "Garota Transou Com Novo Namorada Da Sua Mãe Para Se Livrar Dele", "tipo": "movies" },
    { "id": 311240, "nome": "Milf Gostosa Ajudou Seu Filho, Fodendo Com Ele Para Abaixar Sua Ereção", "tipo": "movies" },
    { "id": 311234, "nome": "Ajudando A Irmã A Se Exercitar", "tipo": "movies" },
    { "id": 311235, "nome": "Estrela Pornô E Sua Amiga, Deram O Cu Pro Seu Novo Agente", "tipo": "movies" },
    { "id": 311231, "nome": "Mamãe Dando De Mamar Pra Dois", "tipo": "movies" },
    { "id": 311232, "nome": "Irmão Ajudando Na Decoração De Natal – Familytherapy", "tipo": "movies" },
    { "id": 311229, "nome": "Irmãos Dormiram Pelados Na Mesma Cama, E Isso Deu Em Sexo", "tipo": "movies" },
    { "id": 311233, "nome": "Enteado Fazendo A Madrasta Gozar Várias Vezes", "tipo": "movies" },
    { "id": 311230, "nome": "Garota Transou Com Seu Irmão Para Fazer Ciúmes Na Amiga", "tipo": "movies" },
    { "id": 311224, "nome": "Empregada Colombiana Fez A Faxina Pelada E Depois Fodeu Com Patrão", "tipo": "movies" },
    { "id": 311226, "nome": "Novinha Lésbica Ficou Com A Mulher Do Pastor", "tipo": "movies" },
    { "id": 311223, "nome": "Eu Vou Te Dar O Que Ela Não Pode – Dadcrush", "tipo": "movies" },
    { "id": 311222, "nome": "Menina Gata, Ensinou Seu Irmão Virgem Como Se Transa", "tipo": "movies" },
    { "id": 311219, "nome": "desejos ocultos de uma mãe", "tipo": "movies" },
    { "id": 311220, "nome": "Dando Pro Novo Padrasto Sem A Mãe Perceber", "tipo": "movies" },
    { "id": 311218, "nome": "Garota Deu Pro Sogro Para Ganhar A Aprovação Dele", "tipo": "movies" },
    { "id": 311214, "nome": "Comendo A Irmã Para Ficar De Bico Fechado", "tipo": "movies" },
    { "id": 311216, "nome": "Imão Fode A Irmã Com Força", "tipo": "movies" },
    { "id": 311212, "nome": "Chamou Irmão De Viado E Tomou Pau Na Buceta", "tipo": "movies" },
    { "id": 311213, "nome": "Comendo A Boceta Da Irmã Adotiva", "tipo": "movies" },
    { "id": 311209, "nome": "Meia-irmã Pedindo Para Alargar A Bucetinha – Brattysis", "tipo": "movies" },
    { "id": 311211, "nome": "Gozando Dentro Da Bucetinha Da Irmã", "tipo": "movies" },
    { "id": 311210, "nome": "Fodendo A Babá Gostosa Presa Na Pia", "tipo": "movies" },
    { "id": 311206, "nome": "dando uma mãozinha pro filho", "tipo": "movies" },
    { "id": 311207, "nome": "Dando o Bucetão Para o Irmão Sortudo", "tipo": "movies" },
    { "id": 311202, "nome": "Brincando de verdade ou desafio com a madrasta – FamilyTherapy", "tipo": "movies" },
    { "id": 311199, "nome": "Garota Insatisfeita Com Namorado, Fez O Irmão Comer Ela", "tipo": "movies" },
    { "id": 311189, "nome": "Meia-irmã Ajudando A Esquecer A Namorada – Meanawolf", "tipo": "movies" },
    { "id": 311190, "nome": "O Patrão Comeu O Cuzinho Da Empregada", "tipo": "movies" },
    { "id": 311188, "nome": "Ajudando A Irmãzinha", "tipo": "movies" },
    { "id": 311187, "nome": "Novinha Foi Dormir Na Cama Da Mãe Para Dar Pro Padrasto", "tipo": "movies" },
    { "id": 311182, "nome": "Enteado Voltou Pra Casa E Fodeu O Cuzinho Da Madrasta – Analmom", "tipo": "movies" },
    { "id": 311179, "nome": "Garota Começou A Transar Com O Irmão Na Frente Da Amiga", "tipo": "movies" },
    { "id": 311176, "nome": "Após Garota Tomar Bolo De Cara No Halloween, Ela Fodeu Com Seu Irmão", "tipo": "movies" },
    { "id": 311175, "nome": "Fugiu Da Prisão Pra Foder A Madrasta – Familysinners", "tipo": "movies" },
    { "id": 311177, "nome": "brincando com minha irmã", "tipo": "movies" },
    { "id": 311172, "nome": "Amaldiçoou A Amiga Para Que Nascesse Um Pau Nela – Futanari", "tipo": "movies" },
    { "id": 311169, "nome": "A Irmãzinha Fez Cu Do Doce No Começo, Mas No Final Acabou Dando Para Seu Irmão", "tipo": "movies" },
    { "id": 311170, "nome": "Aeromoça Traiu Seu Namorado Com Homem Que Ofereceu Dinheiro Por Sexo", "tipo": "movies" },
    { "id": 311171, "nome": "Missax - Rachel Cavalli, Kit Mercer – Initiation Pt. 1", "tipo": "movies" },
    { "id": 311165, "nome": "Irmã Biscate Querendo Rola Na Bunda", "tipo": "movies" },
    { "id": 311168, "nome": "Irmão Ficando No Lugar Do Espantalho Para Foder A Irmã E A Amiga Dela", "tipo": "movies" },
    { "id": 311166, "nome": "Trans Seduzindo A Amiga Para Fazer Sexo A Três", "tipo": "movies" },
    { "id": 311167, "nome": "Gata Russa Transa Com Massagista No Caminhão Da Massagem", "tipo": "movies" },
    { "id": 311161, "nome": "A Primeira Gozada Do Ano – Myfamilypies", "tipo": "movies" },
    { "id": 311159, "nome": "A Madrasta Pegou Seu Enteado Assistindo Pornô, E Decidiu Ajuda-lo A Se Aliviar", "tipo": "movies" },
    { "id": 311163, "nome": "Minha Irmã Quer Saber Como É Meu Leitinho Quente", "tipo": "movies" },
    { "id": 311162, "nome": "Catando A Irmã Pelada Na Aula Online", "tipo": "movies" },
    { "id": 311155, "nome": "Negão Comeu O Cuzinho Da Namorada E Da Amiga Dela", "tipo": "movies" },
    { "id": 311156, "nome": "Médico Inseminando Loirinha Gostosa", "tipo": "movies" },
    { "id": 311154, "nome": "Gostosa Deu Viagra Pro Irmão Tomar, Então Teve Que Foder Com Ele", "tipo": "movies" },
    { "id": 311150, "nome": "Comendo a Irmã e sua Amiga Novinha", "tipo": "movies" },
    { "id": 311145, "nome": "Mulher Deu O Cu Para Conseguir O Empréstimo", "tipo": "movies" },
    { "id": 311148, "nome": "Milf Gostosa Fodeu Com O Funcionário Da Lanchonete", "tipo": "movies" },
    { "id": 311144, "nome": "Casada Traiu O Marido Para Eles Não Serem Despejados", "tipo": "movies" },
    { "id": 311146, "nome": "Irmãzinha Usou O Yoga Para Se Esfregar No Seu Irmão, Ele Não Resistiu E Transou Com Ela", "tipo": "movies" },
    { "id": 311139, "nome": "Endurecendo O Pau Do Irmão", "tipo": "movies" },
    { "id": 311140, "nome": "O Médico Comeu A Sua Paciente", "tipo": "movies" },
    { "id": 311143, "nome": "Garota Pediu Pro Irmão Gozar Dentro, E Ele Gozou", "tipo": "movies" },
    { "id": 311141, "nome": "Você Terá Que Aprender A Lição", "tipo": "movies" },
    { "id": 311137, "nome": "Enteado Sente Atração Pela Madrasta", "tipo": "movies" },
    { "id": 311135, "nome": "Fingiu Que Ganhou Na Loteria Para Comer A Irmã", "tipo": "movies" },
    { "id": 311138, "nome": "Assistindo Pornô Com A Irmã Entediada", "tipo": "movies" },
    { "id": 311136, "nome": "Dinheiro para Submissão", "tipo": "movies" },
    { "id": 311134, "nome": "A Trollagem Se Transformou Em Um Ménage", "tipo": "movies" },
    { "id": 311130, "nome": "Irmã Novinha Se Ofereceu Para Lavar As Louças Em Troca De Uma Chupada Na Boceta", "tipo": "movies" },
    { "id": 311129, "nome": "Homem Ajuda Mulher Grávida, E Acaba Transando Com Ela", "tipo": "movies" },
    { "id": 311124, "nome": "Fodendo A Bucetinha Da Irmã", "tipo": "movies" },
    { "id": 311125, "nome": "Gozando Dentro Da Mamãe", "tipo": "movies" },
    { "id": 311127, "nome": "Irmã Cavalona", "tipo": "movies" },
    { "id": 311126, "nome": "Chantageando Mãe E Filha Golpistas", "tipo": "movies" },
    { "id": 311119, "nome": "Batman Vs Superman – Parte 1", "tipo": "movies" },
    { "id": 311123, "nome": "Menina Fodeu Com Seu Irmão Como Pagamento Pelo Dinheiro Que Ele Emprestou Para O Conserto Do Carro", "tipo": "movies" },
    { "id": 311121, "nome": "Hipnotizando A Mamãe Pra Foder Comigo", "tipo": "movies" },
    { "id": 311114, "nome": "Garota Fodeu Com Negão Que Conheceu Nas Férias Em Ibiza - Parte 1", "tipo": "movies" },
    { "id": 311109, "nome": "Milf Safada Aproveitou Da Situação Para Trair O Marido", "tipo": "movies" },
    { "id": 311112, "nome": "Universitária Sem Habilidades De Negociação!", "tipo": "movies" },
    { "id": 311113, "nome": "Dando a virgindade de presente de natal para o papai – DadCrush", "tipo": "movies" },
    { "id": 311104, "nome": "Comendo a Irmã Cavalona Cheia de Tesão", "tipo": "movies" },
    { "id": 311105, "nome": "Grávida Transou Com Outro Cara Na Frente Do Seu Marido Para Conseguir 3 Meses De Alugueis Grátis", "tipo": "movies" },
    { "id": 311100, "nome": "Secretaria Dando Pro Chefe Para Conseguir Férias", "tipo": "movies" },
    { "id": 311096, "nome": "Garota Asiática Fodeu Com O Namorado, Para Convencer Ele A Ir Com Ela Na Casa Dos Seus Pais", "tipo": "movies" },
    { "id": 311098, "nome": "Garota Fodeu Com Seu Irmão Pensando Que Ele Era Seu Namorado", "tipo": "movies" },
    { "id": 311094, "nome": "Contando ao irmão seus desejos impuros", "tipo": "movies" },
    { "id": 311097, "nome": "Dando uma Bucetada no Cacete do Irmão", "tipo": "movies" },
    { "id": 311089, "nome": "Médico Inseminando Mulher Na Frente Do Marido Dela", "tipo": "movies" },
    { "id": 311091, "nome": "Adivinhe De Quem É Essa Boceta?", "tipo": "movies" },
    { "id": 311090, "nome": "Mulher Deu Para O Cara Que Roubou O Carro Da Auto Escola Enquanto Ela Estava Tendo Aula De Direção", "tipo": "movies" },
    { "id": 311087, "nome": "Funcionário Do Prédio Comeu Mulher Presa Na Porta Do Elevador", "tipo": "movies" },
    { "id": 311085, "nome": "Garotão Sortudo Comeu A Irmã E Amiga", "tipo": "movies" },
    { "id": 311086, "nome": "Chantageando A Irmã Stripper", "tipo": "movies" },
    { "id": 311088, "nome": "Amigas Taradas Metendo Com Irmão", "tipo": "movies" },
    { "id": 311082, "nome": "Enteada Tendo Tesão No Padrasto", "tipo": "movies" },
    { "id": 311080, "nome": "Espiando A Enteada Com Câmera Escondida", "tipo": "movies" },
    { "id": 311079, "nome": "Irmã Fazendo Garganta Profunda No Irmão", "tipo": "movies" },
    { "id": 311075, "nome": "A Vida Secreta Das Bonecas – Transfixed", "tipo": "movies" },
    { "id": 311076, "nome": "Caçando Ovos Com O Filho De Uma Forma Diferente", "tipo": "movies" },
    { "id": 311078, "nome": "Mulheres Fizeram Um Showzinho Lésbico, E Depois Transaram Com Seus Namorados No Banheiro Do Boliche", "tipo": "movies" },
    { "id": 311077, "nome": "Minha Irmã Sentou No Meu Pau", "tipo": "movies" },
    { "id": 311070, "nome": "Comendo A Bundinha Loira Da Irmã Safada", "tipo": "movies" },
    { "id": 311066, "nome": "Mãe Punindo A Filha Com Sexo", "tipo": "movies" },
    { "id": 311065, "nome": "Avaliando Se O Pau Do Irmão É Grande – Princesscum", "tipo": "movies" },
    { "id": 311068, "nome": "Insatisfeito Com A Namorada Comeu A Sogra – Brianna Beach", "tipo": "movies" },
    { "id": 311060, "nome": "Mulher Resiste No Começo A Massagem Grátis Mas Se Entrega E Transa Com Massagista", "tipo": "movies" },
    { "id": 311063, "nome": "Ereção Acidental Do Vovô", "tipo": "movies" },
    { "id": 311061, "nome": "Mulher Aceitou Foder Com Desconhecido Na Véspera De Natal", "tipo": "movies" },
    { "id": 311058, "nome": "Irmã Com Os Peitos Perfeitos Queria Esquecer O Namorado Infiel", "tipo": "movies" },
    { "id": 311056, "nome": "dividindo a cama com a irmãzinha lindinha", "tipo": "movies" },
    { "id": 311057, "nome": "Marido Não Quis, Então A Amiga Acabou Com O Tesão Dela – Transangels", "tipo": "movies" },
    { "id": 311051, "nome": "Estreitando A Relação Com Os Pais Adotivos", "tipo": "movies" },
    { "id": 311050, "nome": "Esposa À Venda Katerina", "tipo": "movies" },
    { "id": 311044, "nome": "Brincadeira de Sexo com a Irmã", "tipo": "movies" },
    { "id": 311045, "nome": "Garota Deixou Seu Padrasto Com Tesão Para Fazer Ele Comer Ela", "tipo": "movies" },
    { "id": 311043, "nome": "Meia-irmã Tentando Ser Da Lista Dos Bonzinhos – Brattysis", "tipo": "movies" },
    { "id": 311034, "nome": "Fazendo Massagem No Irmão Querendo Algo Em Troca", "tipo": "movies" },
    { "id": 311036, "nome": "Não Resistiu Ao $$", "tipo": "movies" },
    { "id": 311030, "nome": "Irmãs Safadas Convidam O Irmão Para Festa De Inauguração – Familytherapy", "tipo": "movies" },
    { "id": 311033, "nome": "Garota Recém Adotada Seduziu O Novo Pai", "tipo": "movies" },
    { "id": 311031, "nome": "Médico Fodendo A Namorada Do Paciente", "tipo": "movies" },
    { "id": 311032, "nome": "Negão Comeu Casada A Pedido Do Corno E Gozou Dentro", "tipo": "movies" },
    { "id": 311025, "nome": "Brincando De Verdade Ou Desafio Com A Madrasta – Familytherapy", "tipo": "movies" },
    { "id": 311028, "nome": "Comando A Bundinha Bucetuda Da Irmã", "tipo": "movies" },
    { "id": 311024, "nome": "Irmãos Fodendo A Amiga", "tipo": "movies" },
    { "id": 311027, "nome": "Mamãe Cuidando De Mim", "tipo": "movies" },
    { "id": 311023, "nome": "dando a boceta pro funcionário da imobiliária para não ser despejada", "tipo": "movies" },
    { "id": 311022, "nome": "A Ereção Implacável Do Meu Filho – Missax", "tipo": "movies" },
    { "id": 311020, "nome": "Brasileira Deu O Cu Pro Negão", "tipo": "movies" },
    { "id": 311018, "nome": "Garota Com Baixa Autoestima Recebe Tratamento Especial Do Médico", "tipo": "movies" },
    { "id": 311017, "nome": "Homem Transou Com A Mulher Após Teste De Modelo", "tipo": "movies" },
    { "id": 311015, "nome": "Netinha Seguindo Os Passos Da Vovó Puta", "tipo": "movies" },
    { "id": 311013, "nome": "Cara Sortudo Fode Com 2 Irmãs Gêmeas", "tipo": "movies" },
    { "id": 311009, "nome": "Fodendo A Garota Lésbica No Carro", "tipo": "movies" },
    { "id": 311006, "nome": "Filha Rebelde – Parte Final", "tipo": "movies" },
    { "id": 311008, "nome": "comi novamente a mãe da minha amiga", "tipo": "movies" },
    { "id": 311003, "nome": "O Enteado Comeu O Cuzinho Da Madrasta Que Estava Com Tesão", "tipo": "movies" },
    { "id": 311002, "nome": "comendo a garota grávida", "tipo": "movies" },
    { "id": 311000, "nome": "Fodendo A Madrasta Antes De Ir Para O Colégio", "tipo": "movies" },
    { "id": 310998, "nome": "Botando A Pistola Na Buceta Da Irmã", "tipo": "movies" },
    { "id": 310996, "nome": "Minha Madrasta Gostosa – Parte 1", "tipo": "movies" },
    { "id": 310995, "nome": "Garota Linda Aceitou Transar Para Ter Suas Dívidas Apagadas Do Sistema", "tipo": "movies" },
    { "id": 310992, "nome": "Ensinando Como Recompensar – Momswap", "tipo": "movies" },
    { "id": 310991, "nome": "Moreninha Gostosa Resiste No Começo Mas Acaba Fodendo Com O Massagista", "tipo": "movies" },
    { "id": 310989, "nome": "Enteada Com Dúvidas Sobre Sexo Anal – Dadcrush", "tipo": "movies" },
    { "id": 310986, "nome": "Guarda Comeu Mãe E Filha Ladras", "tipo": "movies" },
    { "id": 310988, "nome": "A Irmã Salva Vidas", "tipo": "movies" },
    { "id": 310987, "nome": "Ganhei A Aposta E Comi A Mamãe", "tipo": "movies" },
    { "id": 310984, "nome": "Novinha Safadinha Deu Pro Padrasto Enquanto Falava Com A Mãe No Telefone", "tipo": "movies" },
    { "id": 310981, "nome": "Mãe Ensinando Filho E Filha A Meter", "tipo": "movies" },
    { "id": 310979, "nome": "Garota Fingiu Que Estava Doente Para Foder Com Irmão", "tipo": "movies" },
    { "id": 310974, "nome": "Comendo A Garota Grávida", "tipo": "movies" },
    { "id": 310975, "nome": "Asiática Com Peitos Enormes Gravou Pornô Dando O Cuzinho", "tipo": "movies" },
    { "id": 310976, "nome": "Mamãe Sabe O Que É Melhor (parte 2) – Primalfetish", "tipo": "movies" },
    { "id": 310970, "nome": "Mulher Em Processo De Separação Gravou A Foda Com Outro Cara, Para Enviar Para Seu Marido", "tipo": "movies" },
    { "id": 310969, "nome": "Fodendo A Buceta Da Irmã", "tipo": "movies" },
    { "id": 310972, "nome": "Aproveitou Que A Mãe Estava Longe E Chamou O Pai Pra Foder", "tipo": "movies" },
    { "id": 310966, "nome": "Mulher Branquinha Aceita Massagem Grátis E Fode No Caminhão Da Massagem", "tipo": "movies" },
    { "id": 310965, "nome": "O Cara Flagrou Sua Irmã Fazendo Vídeo Pelada, Não Resistiu E Fodeu Ela", "tipo": "movies" },
    { "id": 310964, "nome": "Morena Gata Ajudou Seu Irmão Com O Braço Quebrado A Satisfazer Suas Necessidades", "tipo": "movies" },
    { "id": 310968, "nome": "Chamando Meu Meio-irmão Para Comer Minha Torta – Brattysis", "tipo": "movies" },
    { "id": 310962, "nome": "Milf Deu Pro Enteado Após Descobrir Traição Do Marido", "tipo": "movies" },
    { "id": 310959, "nome": "Metendo Na Irmã E Na Amiga", "tipo": "movies" },
    { "id": 310963, "nome": "Fodendo A Mamãe No Ano Novo", "tipo": "movies" },
    { "id": 310954, "nome": "Enteada Safada Atiçou O Padrasto, Ele Não Aguentou A Tentação E Fodeu Ela", "tipo": "movies" },
    { "id": 310957, "nome": "Café Da Manhã Em Família", "tipo": "movies" },
    { "id": 310958, "nome": "Garota Convenceu Sua Amiga A Participar Da Foda Com Seu Irmão", "tipo": "movies" },
    { "id": 310953, "nome": "Fazendo Yoga Com O Sogro Novo – Digitalplayground", "tipo": "movies" },
    { "id": 310951, "nome": "Novinha Perdeu Virgindade Com Médico", "tipo": "movies" },
    { "id": 310949, "nome": "Matando O Tesão Da Madrasta Boa De Buceta", "tipo": "movies" },
    { "id": 310944, "nome": "Garota Começou A Se Masturbar Durante A Aula De Direção", "tipo": "movies" },
    { "id": 310948, "nome": "Irmã Ninfeta Atacando O Cacete Do Irmão", "tipo": "movies" },
    { "id": 310947, "nome": "Irmã Carente De Sexo Na Pandemia", "tipo": "movies" },
    { "id": 310946, "nome": "Garota Recém Saída Da Prisão Necessitando De Uma Boa Foda", "tipo": "movies" },
    { "id": 310943, "nome": "O Cara Pegou No Flagra Sua Irmã E Sua Namorada Se Pegando, E Depois Fodeu Com As Duas", "tipo": "movies" },
    { "id": 310939, "nome": "Imigrante Ilegal Aceitou A Proposta Para Ajudar Sua Família", "tipo": "movies" },
    { "id": 310940, "nome": "Fodendo A Mãe Cheia De Tesão", "tipo": "movies" },
    { "id": 310935, "nome": "Mamãe Sabe O Que É Melhor (parte1) – Primalfetish", "tipo": "movies" },
    { "id": 310934, "nome": "café da manhã em família", "tipo": "movies" },
    { "id": 310937, "nome": "Irmã Mais Velha Enrabando O Irmão", "tipo": "movies" },
    { "id": 310929, "nome": "Irmão Realizou A Fantasia De Sua Irmã, Em Foder Com Ele De Olhos Vendados", "tipo": "movies" },
    { "id": 310931, "nome": "dona de casa gostosa gravou filme pornô", "tipo": "movies" },
    { "id": 310933, "nome": "Garota Fodeu Com Negão Que Conheceu Nas Férias Em Ibiza - Parte 2", "tipo": "movies" },
    { "id": 310932, "nome": "Arrombando O Tesão Da Buceta Da Irmã", "tipo": "movies" },
    { "id": 310924, "nome": "O Melhor Chá De Buceta Das Primas", "tipo": "movies" },
    { "id": 310926, "nome": "Irmã Gostosa Provocou O Irmão E Teve O Que Mereceu", "tipo": "movies" },
    { "id": 310927, "nome": "Comendo o Bundão Redondo da Irmã", "tipo": "movies" },
    { "id": 310928, "nome": "Fake Taxi – Christine", "tipo": "movies" },
    { "id": 310925, "nome": "Café ou sexo – MyFamilyPies", "tipo": "movies" },
    { "id": 310919, "nome": "A Netinha Estava Com Tesão", "tipo": "movies" },
    { "id": 310921, "nome": "Negão Satisfazendo A Mulher Do Corno", "tipo": "movies" },
    { "id": 310922, "nome": "Fodendo As Gêmeas Universitárias Que Estavam Indo Fazer Prova De Matemática", "tipo": "movies" },
    { "id": 310923, "nome": "Enteado Descobriu A Infidelidade Da Madrasta Ninfomaníaca", "tipo": "movies" },
    { "id": 310915, "nome": "Tirando A Irmãzinho Do Tédio", "tipo": "movies" },
    { "id": 310918, "nome": "De volta dos mortos – PureTaboo", "tipo": "movies" },
    { "id": 310916, "nome": "Garota Lésbica Experimentando O Pau Do Amigo", "tipo": "movies" },
    { "id": 310913, "nome": "Chantageando A Minha Mãe Traidora", "tipo": "movies" },
    { "id": 310912, "nome": "Comendo A Boceta Da Madrasta A Força", "tipo": "movies" },
    { "id": 310909, "nome": "Garçonete Adorou Chupar O Pau E Dar A Boceta Em Local Público", "tipo": "movies" },
    { "id": 310910, "nome": "Enteada Delicadinha Deu Para Seu Padrasto, No Dia Do Seu Aniversário", "tipo": "movies" },
    { "id": 310907, "nome": "O Cara Ajudou A Garota Em Apuros, Pois Sua Reserva De Hotel Foi Cancelada De Última Hora", "tipo": "movies" },
    { "id": 310908, "nome": "Novinha Virgem Pagando A Dívida Do Namorado Com A Bocetinha", "tipo": "movies" },
    { "id": 310904, "nome": "Após Chegar Bêbada Da Balada, A Madrasta Gostosa Fodeu Com Seu Enteado", "tipo": "movies" },
    { "id": 310903, "nome": "Cara Foi Passar Um Tempo Na Casa Do Novo Irmão E Comeu A Filha Dele", "tipo": "movies" },
    { "id": 310902, "nome": "O Cara Tomou Bolo Dos Amigos, Mas Conseguiu Comer Sua Mãe", "tipo": "movies" },
    { "id": 310901, "nome": "Comendo o Cuzão da Irmã e da Amiga", "tipo": "movies" },
    { "id": 310900, "nome": "dando uma lição na amiga da filha", "tipo": "movies" },
    { "id": 310897, "nome": "Comendo a Putinha da Irmã e Amiga", "tipo": "movies" },
    { "id": 310889, "nome": "Fodendo A Minha Irmã E A Amiga", "tipo": "movies" },
    { "id": 310892, "nome": "Comendo o Bucetão das Irmãs", "tipo": "movies" },
    { "id": 310887, "nome": "Empregada Rabuda Quis Experimentar O Pauzão Do Patrão", "tipo": "movies" },
    { "id": 310886, "nome": "Catando A Irmã Molhadinha E Sozinha Em Casa", "tipo": "movies" },
    { "id": 310884, "nome": "Garota Fez Uma Pegadinha Com Se Irmão, E Depois Ele Se Vingou Dela", "tipo": "movies" },
    { "id": 310882, "nome": "Pedindo Permissão Para Gozar", "tipo": "movies" },
    { "id": 310883, "nome": "Comendo a Mãe com Força Super Gostosa", "tipo": "movies" },
    { "id": 310881, "nome": "A Grande Ideia Do Meio-irmão – Cumswappingsis", "tipo": "movies" },
    { "id": 310878, "nome": "Atiçando O Meio Irmão Para Foder Com Ele", "tipo": "movies" },
    { "id": 310876, "nome": "Metendo Com Força Na Enteada Bucetuda", "tipo": "movies" },
    { "id": 310870, "nome": "Casada Ficou Com Negão Na Balada E Levou Pra Casa", "tipo": "movies" },
    { "id": 310872, "nome": "Garota Lindinha Deu O Cuzinho No Teste Do Sofá", "tipo": "movies" },
    { "id": 310864, "nome": "Seduzindo O Padrasto Enquanto A Mãe Está Fora", "tipo": "movies" },
    { "id": 310865, "nome": "Masturbando Com A Irmã Gostosa", "tipo": "movies" },
    { "id": 310866, "nome": "Irmã Gostou De Masturbar O Seu Irmão, E No Dia Seguinte Fez O Serviço Completo", "tipo": "movies" },
    { "id": 310867, "nome": "Flagrou A Irmã Dando Pro Namorado E Comeu Ela Também", "tipo": "movies" },
    { "id": 310862, "nome": "Minha Nova Madrasta É Uma Ninfomaníaca", "tipo": "movies" },
    { "id": 310860, "nome": "Garota Ficou Grávida Do Pai Adotivo Para Ajudar A Mãe Infértil", "tipo": "movies" },
    { "id": 310855, "nome": "Deixando a Mãe Pelada e Fodendo", "tipo": "movies" },
    { "id": 310854, "nome": "Arrombando A Bucetia Das Irmãs", "tipo": "movies" },
    { "id": 310852, "nome": "Brincadeira De Sexo Com A Irmã", "tipo": "movies" },
    { "id": 310846, "nome": "Irmã Com Tesão Goza No Pau Do Irmão", "tipo": "movies" },
    { "id": 310844, "nome": "A Esposa Do Dono Do Puteiro Não Resistiu Ao Dinheiro E Fodeu Com Cliente", "tipo": "movies" },
    { "id": 310837, "nome": "Aeromoça Gata Fudeu Com Taxista Para Ganhar 3 Meses De Corridas Grátis", "tipo": "movies" },
    { "id": 310830, "nome": "Irmã Gostosa Precisando De Dinheiro Para Pagar Multa De Trânsito", "tipo": "movies" },
    { "id": 310832, "nome": "Esses Peitos São Perfeitos", "tipo": "movies" },
    { "id": 310829, "nome": "Fodendo A Minha Mãe Antes Da Faculdade", "tipo": "movies" },
    { "id": 310827, "nome": "Garota Transou Com Irmão Em Troca Dele Fazer Suas Tarefas", "tipo": "movies" },
    { "id": 310823, "nome": "Chantageando A Irmãzinha Gostosinha", "tipo": "movies" },
    { "id": 310821, "nome": "Enquanto Sua Mãe Estava Dormindo, Garota Safada Estava Levando Pau Do Padrasto", "tipo": "movies" },
    { "id": 310819, "nome": "Cara Flagrou A Irmã Se Masturbando De Madrugada", "tipo": "movies" },
    { "id": 310814, "nome": "Comendo A Irmã Gostosa Na Mesma Cama", "tipo": "movies" },
    { "id": 310816, "nome": "Garota Fodeu Com Irmão No Banheiro", "tipo": "movies" },
    { "id": 310815, "nome": "Instrutor De Direção Fodendo Loirinha Para Não Ser Denunciado", "tipo": "movies" },
    { "id": 310811, "nome": "Fodendo A Irmã Gostosa Que Estava Se Exercitando", "tipo": "movies" },
    { "id": 310813, "nome": "O Enteado Acordou Todo Melado De Porra, E Sua Madrasta Gostosa Se Ofereceu Para Terminar O Serviço", "tipo": "movies" },
    { "id": 310812, "nome": "Mãe Flagrou A Filha Transando – Parte 1", "tipo": "movies" },
    { "id": 310807, "nome": "Babá Satisfazendo O Patrão Para Continuar No Trabalho", "tipo": "movies" },
    { "id": 310805, "nome": "Fodendo A Irmãzinha Presa Na Pia Da Cozinha", "tipo": "movies" },
    { "id": 310808, "nome": "Garota Deu O Cuzinho Para Se Livrar Da Acusação De Roubo", "tipo": "movies" },
    { "id": 310799, "nome": "Botando O Pau Na Gostosa Da Irmã", "tipo": "movies" },
    { "id": 310803, "nome": "Encoxou A Mãe Na Pia", "tipo": "movies" },
    { "id": 310801, "nome": "Irmã Ficou Pelada Enquanto Dividia O Cobertor Com Seu Irmão, E Isso Acabou Em Sexo", "tipo": "movies" },
    { "id": 310797, "nome": "Chantageando A Vizinha Muçulmana", "tipo": "movies" },
    { "id": 310798, "nome": "O Padrasto Fodeu A Sua Enteada Que Estava Fazendo Vídeos Sensuais Para Internet", "tipo": "movies" },
    { "id": 310794, "nome": "Fodeu A Irmãzinha E No Final Gozou Dentro", "tipo": "movies" },
    { "id": 310791, "nome": "A Adotiva Com Vícios", "tipo": "movies" },
    { "id": 310789, "nome": "Novinha Inocente Transa Com Massagista Após Deixa-la Excitada", "tipo": "movies" },
    { "id": 310790, "nome": "Babá Fazendo Hora Extra Para Comprar Um Carro", "tipo": "movies" },
    { "id": 310787, "nome": "Menina Safada Se Ofereceu Para Seu Professor De Francês, Ele Não Conseguiu Resistir E Fodeu Ela", "tipo": "movies" },
    { "id": 310781, "nome": "Garota Viu Foto Do Pau Do Irmão E Quis Experimentar", "tipo": "movies" },
    { "id": 310783, "nome": "Férias De Verão Com A Mamãe", "tipo": "movies" },
    { "id": 310780, "nome": "Fazendo O Irmão Brincar Com O Vibrador Virtual Sem Ele Saber – Brattysis", "tipo": "movies" },
    { "id": 310779, "nome": "Mãe Galopando No Macho Da Filha", "tipo": "movies" },
    { "id": 310774, "nome": "Tirando A Virgindade Do Cu Da Irmã", "tipo": "movies" },
    { "id": 310776, "nome": "Assistindo A Filha Ser Fodida Pelo Negão Na Entrevista De Emprego", "tipo": "movies" },
    { "id": 310770, "nome": "Chantageando A Irmã Grávida", "tipo": "movies" },
    { "id": 310772, "nome": "Garota Fodeu Com Seus Pais Adotivos Para Fazer Eles Adotarem Também Seu Irmão", "tipo": "movies" },
    { "id": 310768, "nome": "comendo as gêmeas selvagens", "tipo": "movies" },
    { "id": 310766, "nome": "Fodendo A Irmã Antes De Ir Para Escola", "tipo": "movies" },
    { "id": 310763, "nome": "Branquinha Tatuada Dando Pro Mecânico", "tipo": "movies" },
    { "id": 310755, "nome": "Fodeu A Irmã Gatinha E Gozou Dentro", "tipo": "movies" },
    { "id": 310754, "nome": "Comendo as Irmãs no Dia dos Namorados", "tipo": "movies" },
    { "id": 310758, "nome": "Menina Fez Sexo Com O Padrasto Para Se Livrar De Punição", "tipo": "movies" },
    { "id": 310756, "nome": "Garota Adorou A Punição Dada Pelo Padrasto", "tipo": "movies" },
    { "id": 310753, "nome": "Medicando A Minha Irmã Com Sexo", "tipo": "movies" },
    { "id": 310751, "nome": "comendo a minha irmã mais velha", "tipo": "movies" },
    { "id": 310749, "nome": "Comendo A Garota Má", "tipo": "movies" },
    { "id": 310747, "nome": "Botando A Pica Na Buceta Da Irmã", "tipo": "movies" },
    { "id": 310746, "nome": "Garotas Deram Pro Negão Para Ganhar Carona Para Las Vegas", "tipo": "movies" },
    { "id": 310741, "nome": "Enfiando A Rola Na Bundinha Das Irmã", "tipo": "movies" },
    { "id": 310743, "nome": "Garota Traiu Seu Namorado Famoso Para Não Ir Pra Cadeia", "tipo": "movies" },
    { "id": 310742, "nome": "Irmão Comendo A Xota Da Irmã Loira", "tipo": "movies" },
    { "id": 310739, "nome": "Garota Deu Pro Irmão Enquanto Sua Amiga Estava Dormindo Ao Lado", "tipo": "movies" },
    { "id": 310738, "nome": "Garota Descobriu Que Seu Padrasto Assiste Pornô De Enteada", "tipo": "movies" },
    { "id": 310736, "nome": "Mulher Aceitou Foder Com Fotógrafo Para Ser Capa Da Playboy", "tipo": "movies" },
    { "id": 310729, "nome": "Fazendo O Enteado Gozar Antes Do Date – Familytherapy", "tipo": "movies" },
    { "id": 310731, "nome": "Após Ficar Desemprega Por Causa Da Pandemia, Mulher Começou A Gravar Pornô Com Seu Namorado Para Gan", "tipo": "movies" },
    { "id": 310730, "nome": "Irmãos Nerds Se Vingam Dos Valentões Da Escola – Sisswap", "tipo": "movies" },
    { "id": 310725, "nome": "Por Que Seu Pau Está Pra Fora", "tipo": "movies" },
    { "id": 310726, "nome": "comeu a melhor amiga da mãe que estava com tesão", "tipo": "movies" },
    { "id": 310722, "nome": "Mamãe Vai Te Recompensar Se Tirar Boas Notas Na Escola – Xevbellringer", "tipo": "movies" },
    { "id": 310716, "nome": "Após Sessão De Fotos, Patricinha Deu Gostoso Pro Seu Irmão", "tipo": "movies" },
    { "id": 310715, "nome": "Mamãe Me Seduzindo", "tipo": "movies" },
    { "id": 310714, "nome": "A Vingança Da Mulher Traída, Foi Melhor Do Que O Planejado", "tipo": "movies" },
    { "id": 310713, "nome": "Garota Rebelde Passando Por Reeducação", "tipo": "movies" },
    { "id": 310711, "nome": "Vadia Dando Pro Negão Na Frente Do Pai E Do Irmão", "tipo": "movies" },
    { "id": 310709, "nome": "Garota Muçulmana Apostou Que Não Ficaria Excitada", "tipo": "movies" },
    { "id": 310712, "nome": "Proposta Indecente Da Enteada Tímida", "tipo": "movies" },
    { "id": 310710, "nome": "Ajudando A Mamãe A Montar A Árvore De Natal", "tipo": "movies" },
    { "id": 310707, "nome": "Garota Safada Deu Pro Novo Namorado Da Sua Mãe E Levou Gozada Dentro Da Boceta", "tipo": "movies" },
    { "id": 310708, "nome": "Minha Madrasta Quer Um Presente De Dia Dos Namorados – Brattymilf", "tipo": "movies" },
    { "id": 310701, "nome": "Eu Posso Gozar Papai? – Missax", "tipo": "movies" },
    { "id": 310702, "nome": "Irmã Chantageando O Irmão Com O Bucetão", "tipo": "movies" },
    { "id": 310694, "nome": "Minha Primeira Vez Com Meu Irmão", "tipo": "movies" },
    { "id": 310698, "nome": "O Negão Comeu A Empregada Colombiana", "tipo": "movies" },
    { "id": 310697, "nome": "Fazendo Um Dinheiro Extra Com O Pau Do Meio-irmão – Brattysis", "tipo": "movies" },
    { "id": 310696, "nome": "Assistente Asiática Entrou Na Sala Secreta Do Seu Chefe, E Como Pedido De Desculpas, Deu O Cu Pra El", "tipo": "movies" },
    { "id": 310695, "nome": "Garota Deitou Do Lado Do Irmão Só De Calcinha E Deixou Ele Excitado", "tipo": "movies" },
    { "id": 310690, "nome": "Garota Implorou Para Seu Irmão Foder Ela Com Seu Pau Grande", "tipo": "movies" },
    { "id": 310689, "nome": "Garota Teve Que Dar Pro Segurança Da Loja Para Não Ser Denunciada A Policia Por Roubo", "tipo": "movies" },
    { "id": 310692, "nome": "Chantageando A Amiga Da Irmã Que Traiu O Namorado", "tipo": "movies" },
    { "id": 310686, "nome": "Não Goze Na Camisinha, Goze Em Mim – Mypervyfamily", "tipo": "movies" },
    { "id": 310687, "nome": "Dividindo a Rola do Irmão", "tipo": "movies" },
    { "id": 310679, "nome": "Família Postiça Comemorando O Dia Dos Pais", "tipo": "movies" },
    { "id": 310683, "nome": "Guiando A Punheta Do Filho Com Tesão", "tipo": "movies" },
    { "id": 310675, "nome": "Novinha Peituda Dá Para Massagista Após A Massagem", "tipo": "movies" },
    { "id": 310674, "nome": "Enfiando A Bucetona No Irmão Caçula", "tipo": "movies" },
    { "id": 310677, "nome": "Novinha Dando A Bocetinha Para Receber Doação Para A Igreja", "tipo": "movies" },
    { "id": 310670, "nome": "Irmã Ninfeta Fazendo Irmão Gozar", "tipo": "movies" },
    { "id": 310673, "nome": "Novinha Da Raba Gigante Gravou Um Filme Pornô", "tipo": "movies" },
    { "id": 310669, "nome": "Mostrando A Minha Meia-irmã O Que Posso Fazer – Puretaboo", "tipo": "movies" },
    { "id": 310666, "nome": "Arrancando O Irmão Do Armario A Força", "tipo": "movies" },
    { "id": 310667, "nome": "Babá Aprontou Na Casa Do Patrão E Teve O Que Mereceu", "tipo": "movies" },
    { "id": 310664, "nome": "Comendo a Irmã do Amigo no Banheiro", "tipo": "movies" },
    { "id": 310660, "nome": "Enquanto Seus Pais Tiravam Fotos Da Páscoa, Garota Safada Sentava No Pau Do Coelho", "tipo": "movies" },
    { "id": 310659, "nome": "Mamãe Matando Meu Tesão", "tipo": "movies" },
    { "id": 310657, "nome": "Garota Traída Pelo Namorado, Se Vingou Fodendo Com O Técnico Da Tv A Cabo", "tipo": "movies" },
    { "id": 310656, "nome": "Comendo a Irmã Gostosa na Mesma Cama", "tipo": "movies" },
    { "id": 310655, "nome": "dando pro padrasto para não ficar de castigo", "tipo": "movies" },
    { "id": 310658, "nome": "Casada Dando Pro Personal Trainer Para Ganhar Treinos Grátis", "tipo": "movies" },
    { "id": 310650, "nome": "Irmã Deixando O Pau Do Irmão Durinho", "tipo": "movies" },
    { "id": 310652, "nome": "Após Ser Traído Pela Namorada Com Um Cara Negro, Ele Ainda Teve Que Assistir A Sua Irmã E Sua Mãe Se", "tipo": "movies" },
    { "id": 310647, "nome": "Irmã Adotiva Cheia De Tesão Metendo Com Irmão", "tipo": "movies" },
    { "id": 310644, "nome": "Irmãzinha Gostosa Com Medo De Estar Grávida – Familytherapy", "tipo": "movies" },
    { "id": 310646, "nome": "Assistindo O Enteado Se Masturbando – Povstory", "tipo": "movies" },
    { "id": 310643, "nome": "cantora gostosa precisando de um empréstimo para fazer um clipe", "tipo": "movies" },
    { "id": 310642, "nome": "Britânica Pedindo Pra Gozar Dentro Da Bucetinha", "tipo": "movies" },
    { "id": 310637, "nome": "Comendo A Putinha Da Irmã E Amiga", "tipo": "movies" },
    { "id": 310636, "nome": "Escola De Verão", "tipo": "movies" },
    { "id": 310634, "nome": "Negão Comeu Casadinha Linda A Pedido Do Marido", "tipo": "movies" },
    { "id": 310633, "nome": "Loira Gatinha Foi Experimentar O Viagra Feminino Por Curiosidade E Fodeu Com O Médico", "tipo": "movies" },
    { "id": 310631, "nome": "Comendo A Bunda Da Irmã", "tipo": "movies" },
    { "id": 310626, "nome": "O Novo Emprego Da Irmã Gostosa", "tipo": "movies" },
    { "id": 310628, "nome": "Enteada Cristã Não Resistiu A Tentação E Deu Pro Padrasto", "tipo": "movies" },
    { "id": 310625, "nome": "Adoção De Barriga De Aluguel", "tipo": "movies" },
    { "id": 310622, "nome": "comendo e gozando dentro da irmã ciumenta", "tipo": "movies" },
    { "id": 310619, "nome": "O Cara Comeu A Universitária Safada Que Estava Estudando Inglês Sem Calcinha No Parque Da Faculdade", "tipo": "movies" },
    { "id": 310620, "nome": "Comendo A Amiga Da Meia-irmã – Stepsiblingscaught", "tipo": "movies" },
    { "id": 310616, "nome": "consolando a madrasta traída", "tipo": "movies" },
    { "id": 310615, "nome": "Cunhada destruidora seduziu o marido da irmã enquanto ela não estava perto – XevBellringer", "tipo": "movies" },
    { "id": 310610, "nome": "Mãe Sentando No Filho Cacetudo", "tipo": "movies" },
    { "id": 310611, "nome": "Atentando O Irmão Com A Bucetinha", "tipo": "movies" },
    { "id": 310612, "nome": "Fodeu A Irmã Vadia Enquanto Ela Falava No Telefone Com O Namorado", "tipo": "movies" },
    { "id": 310613, "nome": "O Padrasto Da Garota Descobriu Que Ela Anda Fazendo Vídeos Sexuais Para Internet, E Ele Se Aproveito", "tipo": "movies" },
    { "id": 310606, "nome": "Garota Teve Que Transar Na Frente Do Seu Pai Para Não Ser Presa Por Roubo", "tipo": "movies" },
    { "id": 310605, "nome": "Fazendo O Irmão Gozar", "tipo": "movies" },
    { "id": 310599, "nome": "Café Ou Sexo – Myfamilypies", "tipo": "movies" },
    { "id": 310597, "nome": "Se Distraindo Com Os Peitões Da Professora Gostosa Durante A Prova", "tipo": "movies" },
    { "id": 310596, "nome": "Morando E Comendo A Meia Irmã Safada", "tipo": "movies" },
    { "id": 310594, "nome": "Chantageando O Papai – Parte 2", "tipo": "movies" },
    { "id": 310598, "nome": "Novinha Roubou Loja E Teve Que Dar O Cuzinho Para Não Ser Presa", "tipo": "movies" },
    { "id": 310590, "nome": "Ganhando Experiência Com A Mamãe", "tipo": "movies" },
    { "id": 310593, "nome": "Garota Com Super Poderes, Fodeu Com Seu Irmão", "tipo": "movies" },
    { "id": 310592, "nome": "Chantageando A Irmã Novinha Após Filmar Ela Se Masturbando", "tipo": "movies" },
    { "id": 310586, "nome": "Ciumes Da Mamãe", "tipo": "movies" },
    { "id": 310587, "nome": "De Ferias com a Meia Irmã Bucetuda", "tipo": "movies" },
    { "id": 310588, "nome": "Ensinando O Enteado A Se Masturbar – Mommyjoi", "tipo": "movies" },
    { "id": 310585, "nome": "Minha Enteada E Um Tesão Metendo", "tipo": "movies" },
    { "id": 310581, "nome": "Garota Deu Pro Avô Para Entrar No Testamento", "tipo": "movies" },
    { "id": 310583, "nome": "Flagrou A Irmã Fazendo Sexo Virtual Com Namorado", "tipo": "movies" },
    { "id": 310576, "nome": "O Cara Descobriu Que Sua Irmã Vai Trabalhar Como Stripper", "tipo": "movies" },
    { "id": 310575, "nome": "Empregada Gostosa Dando O Cuzinho Pro Negão", "tipo": "movies" },
    { "id": 310570, "nome": "A Irmã Nerd Se Masturba Lendo Contos Eróticos", "tipo": "movies" },
    { "id": 310573, "nome": "Ajudando O Enteado Com Problemas Na Escola – Momcomesfirst", "tipo": "movies" },
    { "id": 310568, "nome": "As Garotinhas Do Papai – Familytherapy", "tipo": "movies" },
    { "id": 310564, "nome": "Novinha Foi Convidada Para Uma Massagem Ficou Com Tesão E Deu Para O Massagista", "tipo": "movies" },
    { "id": 310563, "nome": "Irmão Fode A Irmã Bucetuda", "tipo": "movies" },
    { "id": 310562, "nome": "O Pai Faleceu Então O Filho Tomou O Lugar Dele De Foder A Madrasta", "tipo": "movies" },
    { "id": 310554, "nome": "Homem Transou Com Sua Personal Trainer Após Oferecer Dinheiro", "tipo": "movies" },
    { "id": 310557, "nome": "Cama Compartilhada Porta Traseira Aberta – Analmom", "tipo": "movies" },
    { "id": 310552, "nome": "Confissão secreta da madrastra – DatingMyStepson", "tipo": "movies" },
    { "id": 310553, "nome": "Mulher Meteu Com O Medico Após Tomar O Viagra Feminino", "tipo": "movies" },
    { "id": 310550, "nome": "Garota Tatuada Dos Peitões", "tipo": "movies" },
    { "id": 310549, "nome": "Irmão E Irmã Dividindo A Cama", "tipo": "movies" },
    { "id": 310545, "nome": "Filha Adotiva Anseia Por Uma Presença Feminina", "tipo": "movies" },
    { "id": 310539, "nome": "Asiática Sendo Fodida No Hotel", "tipo": "movies" },
    { "id": 310543, "nome": "Marido Viciado Em Sexo – Puretaboo", "tipo": "movies" },
    { "id": 310542, "nome": "Mãe Coroa Se Depilando Na Frente Do Filho Tarado", "tipo": "movies" },
    { "id": 310537, "nome": "Fodendo Em Família", "tipo": "movies" },
    { "id": 310538, "nome": "Garota Dividiu O Pau Do Namorado Com Sua Madrasta", "tipo": "movies" },
    { "id": 310531, "nome": "O Cara Fez A Prova De Matemática Da Sua Irmã Em Troca De Encostar Seu Pau Na Boceta Dela", "tipo": "movies" },
    { "id": 310530, "nome": "Gozando Dentro Da Irmã Bucetuda", "tipo": "movies" },
    { "id": 310528, "nome": "Apostando Uma Foda Quente Com A Irmã Asiática", "tipo": "movies" },
    { "id": 310524, "nome": "Chantageando A Minha Irmã", "tipo": "movies" },
    { "id": 310525, "nome": "Minha Madrasta Gostosa – Parte 2", "tipo": "movies" },
    { "id": 310526, "nome": "Médico Flagrou Novinha Tomando Banho No Seu Banheiro", "tipo": "movies" },
    { "id": 310523, "nome": "Milf Gordelícia Transou Com Seu Enteado Novinho", "tipo": "movies" },
    { "id": 310520, "nome": "Garota Tirou A Virgindade Do Novo Irmão Tímido", "tipo": "movies" },
    { "id": 310519, "nome": "Garota Fodeu Com Padrasto Após Flagrá-lo Se Masturbando Vendo Suas Fotos", "tipo": "movies" },
    { "id": 310517, "nome": "Ajudando A Paciente A Engravidar – Parte Final", "tipo": "movies" },
    { "id": 310511, "nome": "Fazendo A Irmã Foder No Pau", "tipo": "movies" },
    { "id": 310510, "nome": "Mãe Metendo Com O Genro", "tipo": "movies" },
    { "id": 310513, "nome": "Presente De Dia Das Mães Foi Uma Orgia Com A Familia", "tipo": "movies" },
    { "id": 310508, "nome": "Garota Fodeu Com Seu Irmão Antes De Ir Para Escola", "tipo": "movies" },
    { "id": 310504, "nome": "Comendo a Irmã Loira Ladra de Camisinhas", "tipo": "movies" },
    { "id": 310502, "nome": "Acabou De Terminar O Namoro E Pediu Pau Pro Irmão – Xevbellringer", "tipo": "movies" },
    { "id": 310501, "nome": "Noite De Núpcias Adiantada", "tipo": "movies" },
    { "id": 310499, "nome": "Mamãe Noel Traindo O Namorado", "tipo": "movies" },
    { "id": 310503, "nome": "Aliviando O Estresse Do Papai No Trabalho – Primalfetish", "tipo": "movies" },
    { "id": 310496, "nome": "Ensinando Bons Modos Para A Melhor Amiga Da Filha – Adulttime", "tipo": "movies" },
    { "id": 310495, "nome": "O Irmão Chantageou Sua Irmã, Após Ele Descobrir Que Ela Traiu Seu Namorado", "tipo": "movies" },
    { "id": 310494, "nome": "Irmã Gostosa Amassando O Irmão", "tipo": "movies" },
    { "id": 310497, "nome": "O Irmão Flagrou A Sua Irmãzinha Se Masturbando Antes De Dormir", "tipo": "movies" },
    { "id": 310493, "nome": "Mulher Transou Com Taxista Para Ele Apagar O Vídeo Dela Trocando De Roupas", "tipo": "movies" },
    { "id": 310492, "nome": "Novinha Transou Com Cara Para Conseguir Um Empréstimo", "tipo": "movies" },
    { "id": 310484, "nome": "Asiática Chupou O Pau De Seu Colega Como Comemoração Do Dia Do File Com Boquete", "tipo": "movies" },
    { "id": 310487, "nome": "Influencer Gravando Conteúdo Adulto Com Taxista Sortudo", "tipo": "movies" },
    { "id": 310483, "nome": "Metendo Na Madrasta Achando Que Era A Irmã", "tipo": "movies" },
    { "id": 310480, "nome": "Ensinando A Irmãzinha A Ser Uma Boa Esposa", "tipo": "movies" },
    { "id": 310475, "nome": "Foi Fazer Faxina Na Casa Da Amiga E Acabou Virando A Puta Do Casal – Puretaboo", "tipo": "movies" },
    { "id": 310476, "nome": "Descobriu Que O Filho Assiste Incesto E Ficou Com Tesão", "tipo": "movies" },
    { "id": 310477, "nome": "Furando O Bucetão Da Irmã Caçula", "tipo": "movies" },
    { "id": 310474, "nome": "Adotiva Querendo Um Irmão", "tipo": "movies" },
    { "id": 310478, "nome": "O Cara Entrou No Banheiro Quando Sua Irmã Saia Do Banho, E Convenceu Ela A Foder Com Ele", "tipo": "movies" },
    { "id": 310470, "nome": "Forçando Uma Foda Com A Mãe Do Amigo", "tipo": "movies" },
    { "id": 310471, "nome": "Comendo A Buceta Da Irmã Por Acidente", "tipo": "movies" },
    { "id": 310466, "nome": "Ajudando A Enteada Com A Lição De Casa", "tipo": "movies" },
    { "id": 310463, "nome": "Garota Viciada Em Pau Grande, Fez O Irmão Da Amiga Comer Elas", "tipo": "movies" },
    { "id": 310460, "nome": "Eu Te Imploro! Santa Irmã!", "tipo": "movies" },
    { "id": 310462, "nome": "Irmão Amassando A Irmã Bucetuda", "tipo": "movies" },
    { "id": 310454, "nome": "Comendo A Mãe Com Força Super Gostosa", "tipo": "movies" },
    { "id": 310456, "nome": "A Babá Loirinha Transou Com O Patrão, E Fez Ele Gozar Dentro Da Boceta Dela", "tipo": "movies" },
    { "id": 310453, "nome": "comendo a irmã para ficar de bico fechado", "tipo": "movies" },
    { "id": 310449, "nome": "Aceitando O Desafio De Foder A Irmã E Sua Amiga Gostosa", "tipo": "movies" },
    { "id": 310448, "nome": "Mecânico Fode A Buceta Da Loira Em Apuros", "tipo": "movies" },
    { "id": 310450, "nome": "Guerra De Travesseiro Termina Em Sexo – Mommysgirl", "tipo": "movies" },
    { "id": 310444, "nome": "Garota Linda Fez Cu Doce No Começo, Mas Acabou Se Entregando Ao Irmão", "tipo": "movies" },
    { "id": 310446, "nome": "Enteada Ensinando A Usar Cintaralho – Mommysgirl", "tipo": "movies" },
    { "id": 310445, "nome": "Após Matar Aula, Menina Fode Com Seu Padrasto Para Que Ele Não Conte Nada A Sua Mãe", "tipo": "movies" },
    { "id": 310447, "nome": "Estrupando A Bucetona Da Mamãe Legendado", "tipo": "movies" },
    { "id": 310437, "nome": "Gravando Um Pornô Com A Mamãe", "tipo": "movies" },
    { "id": 310440, "nome": "Casada Traiu Seu Marido, Fodendo Com 2 Negões Que Foram Arrumar O Encanamento Da Casa", "tipo": "movies" },
    { "id": 310436, "nome": "Irmã Curiosa", "tipo": "movies" },
    { "id": 310426, "nome": "dois amigos transaram com três mulheres que pegaram carona com eles", "tipo": "movies" },
    { "id": 310425, "nome": "Eu Aposto Que Você Esta Molhada", "tipo": "movies" },
    { "id": 310424, "nome": "Novinha Ladra Traindo O Namorado Para Não Ser Presa", "tipo": "movies" },
    { "id": 310423, "nome": "britânica pedindo pra gozar dentro da bucetinha", "tipo": "movies" },
    { "id": 310420, "nome": "Garota Fodeu Com Padrasto, Enquanto A Mãe Dela Dormia Ao Lado", "tipo": "movies" },
    { "id": 310418, "nome": "O Padre Da Escola Pegou As 2 Garotas No Banheiro Se Beijando, E Como Lição Seus Padrastos Lhe Deram", "tipo": "movies" },
    { "id": 310417, "nome": "Criando vínculos familiares – PervTherapy", "tipo": "movies" },
    { "id": 310414, "nome": "Irmãos Assistindo Filme Pornô Acabou Em Sexo", "tipo": "movies" },
    { "id": 310416, "nome": "Garota Porra-louca Fez Seu Irmão Comer Ela", "tipo": "movies" },
    { "id": 310409, "nome": "Filha Adotiva Recebe Aulas De Reforço", "tipo": "movies" },
    { "id": 310408, "nome": "Comendo A Meia-irmã E A Amiga Vestida De Coelinha", "tipo": "movies" },
    { "id": 310411, "nome": "O Patrão Comeu A Baba Dos Filhos Em Troca De Pagar Sua Faculdade", "tipo": "movies" },
    { "id": 310407, "nome": "Garota Arrumou Seu Quarto Para Ser Fodida Pelo Irmão", "tipo": "movies" },
    { "id": 310406, "nome": "Marido Impotente Deixando O Médico Engravidar Sua Esposa", "tipo": "movies" },
    { "id": 310402, "nome": "Mulher Fode Com Massagista Que Ofereceu Massagem Grátis", "tipo": "movies" },
    { "id": 310404, "nome": "Fodendo Forte A Bucetinha Da Irmã", "tipo": "movies" },
    { "id": 310398, "nome": "Missax - Anny Aurora – Daddys Bad Girl Ii", "tipo": "movies" },
    { "id": 310399, "nome": "Mulher Linda Aceitou Transar Por Dinheiro Em Um Lugar Público", "tipo": "movies" },
    { "id": 310400, "nome": "Médico Sortudo Comeu Sua Paciente E A Enfermeira", "tipo": "movies" },
    { "id": 310387, "nome": "Não Me Espie", "tipo": "movies" },
    { "id": 310385, "nome": "Ajudando A Irmã Safada No Alongamento", "tipo": "movies" },
    { "id": 310388, "nome": "Mulher Tentou Converter Sua Filha Adotiva Lésbica Em Heterossexual", "tipo": "movies" },
    { "id": 310378, "nome": "Metendo Na Irmã Adotada Gostosa", "tipo": "movies" },
    { "id": 310380, "nome": "Comendo o Rabo da Corretora de Imóveis", "tipo": "movies" },
    { "id": 310376, "nome": "brincadeiras sexuais com a mamãe", "tipo": "movies" },
    { "id": 310375, "nome": "Irmão Fazendo Incesto Com Irmã E Amiga Gostosa", "tipo": "movies" },
    { "id": 310373, "nome": "Milf Cavala Traiu O Marido, Para Sua Filha Não Ser Expulsa Da Escola", "tipo": "movies" },
    { "id": 310377, "nome": "Enteada Tem Tesão Em Assistir Outros Transando", "tipo": "movies" },
    { "id": 310374, "nome": "Fodendo A Espiã Gostosa", "tipo": "movies" },
    { "id": 310368, "nome": "Enfiando A Salsicha No Bucetão Da Morena", "tipo": "movies" },
    { "id": 310371, "nome": "Fodeu A Irmãzinha Presa Na Pia E Ela Gostou", "tipo": "movies" },
    { "id": 310366, "nome": "Novinha Deu O Cu Pro Padrasto Para Ele Não Ir Embora De Casa", "tipo": "movies" },
    { "id": 310363, "nome": "Avó E Sua Neta Foram Pegas Roubando Loja", "tipo": "movies" },
    { "id": 310357, "nome": "Casada Cheia De Tesão", "tipo": "movies" },
    { "id": 310349, "nome": "Irmã Cumpriu O Desafio Sem Calcinha", "tipo": "movies" },
    { "id": 310351, "nome": "Ajudando A Colombiana A Aliviar O Tesão", "tipo": "movies" },
    { "id": 310348, "nome": "Fodendo A Funcionária Do Hotel No Banheiro", "tipo": "movies" },
    { "id": 310347, "nome": "Naomi Não Resistiu A Proposta", "tipo": "movies" },
    { "id": 310343, "nome": "Novinha Gata Realizou O Último Desejo Do Seu Irmão", "tipo": "movies" },
    { "id": 310345, "nome": "Minha Enteada Travessa Está Com O Controle Errado! – Mommysgirl", "tipo": "movies" },
    { "id": 310341, "nome": "A Mão Amiga Da Madrasta", "tipo": "movies" },
    { "id": 310338, "nome": "Empurrando Na Minha Meia Irmã", "tipo": "movies" },
    { "id": 310335, "nome": "Aproveitou Que A Cunhada Saiu E Deu Pro Marido Dela – Blacked", "tipo": "movies" },
    { "id": 310333, "nome": "Brincando Com Minha Irmã", "tipo": "movies" },
    { "id": 310332, "nome": "Moeda De Pagamento – Parte Final", "tipo": "movies" },
    { "id": 310329, "nome": "Mia Khalifa Começando No Pornô Com Apoio Do Namorado", "tipo": "movies" },
    { "id": 310331, "nome": "comeu a irmãzinha novinha no banheiro", "tipo": "movies" },
    { "id": 310330, "nome": "Massagista Com Segundas Intenções Oferece Massagem Grátis E Consegue Transar Com Loirinha", "tipo": "movies" },
    { "id": 310322, "nome": "Ninfomaníaca Deu Pro Padre Durante Confissão", "tipo": "movies" },
    { "id": 310323, "nome": "Comendo A Irmã Do Amigo No Banheiro", "tipo": "movies" },
    { "id": 310326, "nome": "comendo a garota má", "tipo": "movies" },
    { "id": 310321, "nome": "Fodendo Com O Enteado Para Sobreviver No Frio Do Natal – Janecane", "tipo": "movies" },
    { "id": 310317, "nome": "Aproveitou Sua Ultima Férias De Verão Para Foder Com O Pai Da Amiga", "tipo": "movies" },
    { "id": 310312, "nome": "Fodendo A Babá E A Irmã Bucetuda", "tipo": "movies" },
    { "id": 310306, "nome": "Comendo A Irmã Cavalona Cheia De Tesão", "tipo": "movies" },
    { "id": 310310, "nome": "Modelo Gostosa Não Resistiu Ao Dinheiro", "tipo": "movies" },
    { "id": 310308, "nome": "Ensinando Sexo Para A Irmã", "tipo": "movies" },
    { "id": 310309, "nome": "Garota Vadia Fez Um Boquete No Padrasto, Enquanto Falava Ao Telefone Com Sua Mãe", "tipo": "movies" },
    { "id": 310301, "nome": "Garota Toda Tatuada Fodeu Com Seu Futuro Padrão", "tipo": "movies" },
    { "id": 310297, "nome": "Empregada Novata Fez A Faxina Pelada E Depois Transou Com O Patrão", "tipo": "movies" },
    { "id": 310290, "nome": "A História Da Empregada Doméstica", "tipo": "movies" },
    { "id": 310289, "nome": "Garçonete Cavala Fodeu Com Dono Da Loja De Penhores Para Conseguir Dinheiro", "tipo": "movies" },
    { "id": 310287, "nome": "Casada Deu O Cuzinho Pro Médico Enquanto Seu Marido Estava Desmaiado", "tipo": "movies" },
    { "id": 310284, "nome": "Atrapalhando A Meia-irmã A Ler – Familytherapy", "tipo": "movies" },
    { "id": 310275, "nome": "Fodendo Estudante Novinha No Porão", "tipo": "movies" },
    { "id": 310280, "nome": "Garota Linda Roubou As Camisinhas Do Seu Irmão", "tipo": "movies" },
    { "id": 310279, "nome": "Cara Convenceu A Namorada A Transar Com O Guarda Para Não Serem Presos", "tipo": "movies" },
    { "id": 310274, "nome": "Grávida Pagando A Dívida Com Sexo", "tipo": "movies" },
    { "id": 310269, "nome": "Mulher Transou Com O Funcionário Do Banco Para Conseguir Um Empréstimo", "tipo": "movies" },
    { "id": 310267, "nome": "Brincadeiras Sexuais Com A Mamãe", "tipo": "movies" },
    { "id": 310261, "nome": "Cama compartilhada porta traseira aberta – AnalMom", "tipo": "movies" },
    { "id": 310258, "nome": "O Enteado Fodeu Com Sua Madrasta Muçulmana Para Ensinar Ela A Satisfazer Sexualmente Seu Pai, E Salv", "tipo": "movies" },
    { "id": 310259, "nome": "cuidando da nora grávida", "tipo": "movies" },
    { "id": 310257, "nome": "Mulher Que Tomou Bolo Do Namorado, Traiu Ele Com Dois Caras Desconhecidos", "tipo": "movies" }
]
;

// --- FUNÇÃO PARA VERIFICAR SE É ADULTO ---
const isAdulto = (nome) => {
    const n = nome.toUpperCase();
    return n.includes('[XXX]') || 
           n.includes('[ADULTO]') || 
           n.includes(' ADULTO') || 
           n.includes('[TRANSEXUAL]') || 
           n.includes('[TRANS]') ||
           n.includes('HENTAI') ||
           n.includes('[SEXO]') ||
           n.includes('PLAYBOY') ||
           n.includes('BRASILEIRINHAS') ||
           n.includes('SEXY HOT');
};

// --- FUNÇÃO PARA PESQUISAR NO BING IMAGES (Alternativa ao Google sem API Key) ---
async function searchBingImages(query) {
    try {
        const url = `https://www.bing.com/images/search?q=${encodeURIComponent(query + " poster")}&first=1`;
        
        const response = await axios.get(url, {
            headers: {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
            }
        });

        // Regex simples para pegar o primeiro link de imagem JPG/PNG
        const regex = /murl&quot;:&quot;(http.*?\.jpg)&quot;/;
        const match = response.data.match(regex);

        if (match && match[1]) {
            return match[1];
        }
        return null;
    } catch (error) {
        return null;
    }
}

// --- FUNÇÃO PARA BAIXAR UMA IMAGEM ---
async function downloadImage(url, filepath) {
    const writer = fs.createWriteStream(filepath);

    const response = await axios({
        url,
        method: 'GET',
        responseType: 'stream',
        timeout: 10000
    });

    response.data.pipe(writer);

    return new Promise((resolve, reject) => {
        writer.on('finish', resolve);
        writer.on('error', reject);
    });
}

// --- FUNÇÃO DE BUSCA DO GOOGLE (VIA BIBLIOTECA g-i-s) ---
function googleImageSearch(query) {
    return new Promise((resolve, reject) => {
        gis(query, (error, results) => {
            if (error) reject(error);
            else resolve(results);
        });
    });
}

// --- PROCESSO PRINCIPAL ---
(async () => {
    console.log("🚀 Iniciando correção de capas...");

    // Verifica se a imagem padrão existe
    if (!fs.existsSync(ARQUIVO_ADULTO_PADRAO)) {
        console.error(`❌ ERRO: Você precisa colocar uma imagem chamada '${ARQUIVO_ADULTO_PADRAO}' na pasta do projeto!`);
        console.error("   Baixe qualquer imagem +18 genérica do Google e salve com esse nome.");
        process.exit(1);
    }

    let contador = 0;

    for (const item of ITENS_PARA_CORRIGIR) {
        contador++;
        const pasta = item.tipo === 'series' ? DIR_SERIES : DIR_FILMES;
        const arquivoFinal = path.join(pasta, `${item.id}.jpg`);

        // Se já existe, pula
        if (fs.existsSync(arquivoFinal)) continue;

        process.stdout.write(`\r[${contador}/${ITENS_PARA_CORRIGIR.length}] Processando: ${item.nome.substring(0, 30)}... `);

        try {
            // CENÁRIO 1: CONTEÚDO ADULTO
            if (isAdulto(item.nome)) {
                // Copia a imagem padrão
                await fs.copy(ARQUIVO_ADULTO_PADRAO, arquivoFinal);
                // process.stdout.write("✅ (Capa Adulta Padrão)");
            } 
            // CENÁRIO 2: CONTEÚDO NORMAL (Busca no Google/Bing)
            else {
                // Tenta g-i-s (Google) primeiro
                try {
                    const results = await googleImageSearch(item.nome + " poster movie");
                    if (results && results.length > 0) {
                        await downloadImage(results[0].url, arquivoFinal);
                        // process.stdout.write("✅ (Google Images)");
                    } else {
                        throw new Error("Sem resultados no Google");
                    }
                } catch (e) {
                    // Fallback para Bing se Google falhar
                    const bingUrl = await searchBingImages(item.nome);
                    if (bingUrl) {
                        await downloadImage(bingUrl, arquivoFinal);
                        // process.stdout.write("✅ (Bing Images)");
                    } else {
                        // process.stdout.write("❌ (Não encontrado)");
                    }
                }
            }

            // Pequena pausa para não ser bloqueado pelo Google
            await new Promise(r => setTimeout(r, DELAY_ENTRE_BUSCAS));

        } catch (error) {
            // process.stdout.write(`❌ Erro: ${error.message}`);
        }
    }

    console.log("\n\n🏁 Correção finalizada! Reinicie o servidor para ver as mudanças.");
})();